# Generated by Django 4.1.1 on 2022-09-23 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank_Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_bank_account', models.IntegerField()),
                ('name_account', models.CharField(max_length=46)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_categories', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Movements_Recorded',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_item', models.CharField(max_length=40)),
                ('type_movimiento', models.SmallIntegerField()),
                ('value_amount', models.BigIntegerField(verbose_name='13')),
                ('id_categories', models.IntegerField()),
                ('data_time', models.DateTimeField()),
                ('id_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_bank_account_movements', to='appOwlTracker.bank_accounts')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
