# Generated by Django 4.1.1 on 2022-09-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOwlTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
